//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.OutputRules
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/OutputRulesSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/OutputRulesSchema", IsNullable = false)]
  public partial class rootmap
  {

    private Initialisation initialisationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Initialisation initialisation
    {
      get
      {
        return this.initialisationField;
      }
      set
      {
        this.initialisationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/OutputRulesSchema")]
  public partial class Initialisation
  {

    private string ownerField;

    private OutputRule[] outputruleField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("outputrule", Order = 1)]
    public OutputRule[] outputrule
    {
      get
      {
        return this.outputruleField;
      }
      set
      {
        this.outputruleField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/OutputRulesSchema")]
  public partial class OutputRule
  {

    private string sourceField;

    private string typeField;

    private string stratumField;

    private string characteristicField;

    private string filenameField;

    private string specification1Field;

    private string specification2Field;

    private OutputRuleReopen reopenField;

    private When whenField;

    /// <remarks/>
    public string source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }

    /// <remarks/>
    public string type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    public string stratum
    {
      get
      {
        return this.stratumField;
      }
      set
      {
        this.stratumField = value;
      }
    }

    /// <remarks/>
    public string characteristic
    {
      get
      {
        return this.characteristicField;
      }
      set
      {
        this.characteristicField = value;
      }
    }

    /// <remarks/>
    public string filename
    {
      get
      {
        return this.filenameField;
      }
      set
      {
        this.filenameField = value;
      }
    }

    /// <remarks/>
    public string specification1
    {
      get
      {
        return this.specification1Field;
      }
      set
      {
        this.specification1Field = value;
      }
    }

    /// <remarks/>
    public string specification2
    {
      get
      {
        return this.specification2Field;
      }
      set
      {
        this.specification2Field = value;
      }
    }

    /// <remarks/>
    public OutputRuleReopen reopen
    {
      get
      {
        return this.reopenField;
      }
      set
      {
        this.reopenField = value;
      }
    }

    /// <remarks/>
    public When when
    {
      get
      {
        return this.whenField;
      }
      set
      {
        this.whenField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/OutputRulesSchema")]
  public enum OutputRuleReopen
  {

    /// <remarks/>
    append,

    /// <remarks/>
    overwrite,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/OutputRulesSchema")]
  public partial class When
  {

    private int countField;

    private string initialtimeField;

    private string itemField;

    private ItemChoiceType itemElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int count
    {
      get
      {
        return this.countField;
      }
      set
      {
        this.countField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string initialtime
    {
      get
      {
        return this.initialtimeField;
      }
      set
      {
        this.initialtimeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("frequency", typeof(string), Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute("interval", typeof(string), Order = 2)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
      get
      {
        return this.itemElementNameField;
      }
      set
      {
        this.itemElementNameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/OutputRulesSchema", IncludeInSchema = false)]
  public enum ItemChoiceType
  {

    /// <remarks/>
    frequency,

    /// <remarks/>
    interval,
  }
}
