//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.Plants
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PlantsSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/PlantsSchema", IsNullable = false)]
  public partial class rootmap
  {

    private Plants constructionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Plants construction
    {
      get
      {
        return this.constructionField;
      }
      set
      {
        this.constructionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/PlantsSchema")]
  public partial class Plants
  {

    private string ownerField;

    private PlantsPlant[] plantField;

    public Plants()
    {
      this.ownerField = "PlantCoordinator";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("plant", Order = 1)]
    public PlantsPlant[] plant
    {
      get
      {
        return this.plantField;
      }
      set
      {
        this.plantField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PlantsSchema")]
  public partial class PlantsPlant
  {

    private string nameField;

    private string typeField;

    private string originField;

    private string seed_locationField;

    private decimal seeding_timeField;

    private Axis[] seminal_axisField;

    private Axis[] nodal_axisField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string origin
    {
      get
      {
        return this.originField;
      }
      set
      {
        this.originField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string seed_location
    {
      get
      {
        return this.seed_locationField;
      }
      set
      {
        this.seed_locationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal seeding_time
    {
      get
      {
        return this.seeding_timeField;
      }
      set
      {
        this.seeding_timeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seminal_axis", Order = 5)]
    public Axis[] seminal_axis
    {
      get
      {
        return this.seminal_axisField;
      }
      set
      {
        this.seminal_axisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nodal_axis", Order = 6)]
    public Axis[] nodal_axis
    {
      get
      {
        return this.nodal_axisField;
      }
      set
      {
        this.nodal_axisField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/PlantsSchema")]
  public partial class Axis
  {

    private decimal start_lagField;

    private decimal probabilityField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public decimal start_lag
    {
      get
      {
        return this.start_lagField;
      }
      set
      {
        this.start_lagField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public decimal probability
    {
      get
      {
        return this.probabilityField;
      }
      set
      {
        this.probabilityField = value;
      }
    }
  }
}
