//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.PlantTypes
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PlantTypesSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/PlantTypesSchema", IsNullable = false)]
  public partial class rootmap
  {

    private PlantTypes constructionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public PlantTypes construction
    {
      get
      {
        return this.constructionField;
      }
      set
      {
        this.constructionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/PlantTypesSchema")]
  public partial class PlantTypes
  {

    private string ownerField;

    private PlantTypesPlanttype[] planttypeField;

    public PlantTypes()
    {
      this.ownerField = "PlantCoordinator";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("planttype", Order = 1)]
    public PlantTypesPlanttype[] planttype
    {
      get
      {
        return this.planttypeField;
      }
      set
      {
        this.planttypeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PlantTypesSchema")]
  public partial class PlantTypesPlanttype
  {

    private string nameField;

    private decimal roots_to_foliage_ratioField;

    private decimal vegetate_to_reproduce_ratioField;

    private decimal structure_to_photosynthesize_ratioField;

    private decimal initial_seminal_deflectionField;

    private decimal germination_lagField;

    private decimal first_seminal_probabilityField;

    private decimal temperature_of_zero_growthField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public decimal roots_to_foliage_ratio
    {
      get
      {
        return this.roots_to_foliage_ratioField;
      }
      set
      {
        this.roots_to_foliage_ratioField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public decimal vegetate_to_reproduce_ratio
    {
      get
      {
        return this.vegetate_to_reproduce_ratioField;
      }
      set
      {
        this.vegetate_to_reproduce_ratioField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public decimal structure_to_photosynthesize_ratio
    {
      get
      {
        return this.structure_to_photosynthesize_ratioField;
      }
      set
      {
        this.structure_to_photosynthesize_ratioField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal initial_seminal_deflection
    {
      get
      {
        return this.initial_seminal_deflectionField;
      }
      set
      {
        this.initial_seminal_deflectionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public decimal germination_lag
    {
      get
      {
        return this.germination_lagField;
      }
      set
      {
        this.germination_lagField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public decimal first_seminal_probability
    {
      get
      {
        return this.first_seminal_probabilityField;
      }
      set
      {
        this.first_seminal_probabilityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public decimal temperature_of_zero_growth
    {
      get
      {
        return this.temperature_of_zero_growthField;
      }
      set
      {
        this.temperature_of_zero_growthField = value;
      }
    }
  }
}
