//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.PostOffice
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PostOfficeSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/PostOfficeSchema", IsNullable = false)]
  public partial class rootmap
  {

    private PostOfficeConstruction constructionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public PostOfficeConstruction construction
    {
      get
      {
        return this.constructionField;
      }
      set
      {
        this.constructionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/PostOfficeSchema")]
  public partial class PostOfficeConstruction
  {

    private string ownerField;

    private PostOfficeConstructionPostoffice postofficeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public PostOfficeConstructionPostoffice postoffice
    {
      get
      {
        return this.postofficeField;
      }
      set
      {
        this.postofficeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/PostOfficeSchema")]
  public partial class PostOfficeConstructionPostoffice
  {

    private uint random_seedField;

    private bool random_seedFieldSpecified;

    private string previousField;

    private string nowField;

    private string next_startField;

    private string next_endField;

    private string defaultruntimeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public uint random_seed
    {
      get
      {
        return this.random_seedField;
      }
      set
      {
        this.random_seedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool random_seedSpecified
    {
      get
      {
        return this.random_seedFieldSpecified;
      }
      set
      {
        this.random_seedFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string previous
    {
      get
      {
        return this.previousField;
      }
      set
      {
        this.previousField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string now
    {
      get
      {
        return this.nowField;
      }
      set
      {
        this.nowField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string next_start
    {
      get
      {
        return this.next_startField;
      }
      set
      {
        this.next_startField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string next_end
    {
      get
      {
        return this.next_endField;
      }
      set
      {
        this.next_endField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string defaultruntime
    {
      get
      {
        return this.defaultruntimeField;
      }
      set
      {
        this.defaultruntimeField = value;
      }
    }
  }
}
