//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.ScoreboardData
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/ScoreboardDataSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardDataSchema", IsNullable = false)]
  public partial class rootmap
  {

    private ScoreboardData[] initialisationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("initialisation", Order = 0)]
    public ScoreboardData[] initialisation
    {
      get
      {
        return this.initialisationField;
      }
      set
      {
        this.initialisationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardDataSchema")]
  public partial class ScoreboardData
  {

    private string ownerField;

    private ScoreboardDataScoreboarddata[] scoreboarddataField;

    public ScoreboardData()
    {
      this.ownerField = "Scoreboard";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("scoreboarddata", Order = 1)]
    public ScoreboardDataScoreboarddata[] scoreboarddata
    {
      get
      {
        return this.scoreboarddataField;
      }
      set
      {
        this.scoreboarddataField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/ScoreboardDataSchema")]
  public partial class ScoreboardDataScoreboarddata
  {

    private string processField;

    private string characteristicField;

    private string schemeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string process
    {
      get
      {
        return this.processField;
      }
      set
      {
        this.processField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string characteristic
    {
      get
      {
        return this.characteristicField;
      }
      set
      {
        this.characteristicField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string scheme
    {
      get
      {
        return this.schemeField;
      }
      set
      {
        this.schemeField = value;
      }
    }
  }
}
