//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.Scoreboards
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema", IsNullable = false)]
  public partial class rootmap
  {

    private Construction constructionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Construction construction
    {
      get
      {
        return this.constructionField;
      }
      set
      {
        this.constructionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema")]
  public partial class Construction
  {

    private string ownerField;

    private Scoreboard scoreboardField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public Scoreboard scoreboard
    {
      get
      {
        return this.scoreboardField;
      }
      set
      {
        this.scoreboardField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema")]
  public partial class Scoreboard
  {

    private string nameField;

    private int stratumField;

    private BoundaryArray[] boundaryarrayField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int stratum
    {
      get
      {
        return this.stratumField;
      }
      set
      {
        this.stratumField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("boundaryarray", Order = 2)]
    public BoundaryArray[] boundaryarray
    {
      get
      {
        return this.boundaryarrayField;
      }
      set
      {
        this.boundaryarrayField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema")]
  public partial class BoundaryArray
  {

    private Dimension dimensionField;

    private string positionarrayField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Dimension dimension
    {
      get
      {
        return this.dimensionField;
      }
      set
      {
        this.dimensionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string positionarray
    {
      get
      {
        return this.positionarrayField;
      }
      set
      {
        this.positionarrayField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/ScoreboardsSchema")]
  public enum Dimension
  {

    /// <remarks/>
    X,

    /// <remarks/>
    Y,

    /// <remarks/>
    Z,
  }
}
