//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.7.2046.0.
//
namespace Rootmap.Configurator.Schema.VolumeObjects
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema", IsNullable = false)]
  public partial class rootmap
  {

    private Construction constructionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Construction construction
    {
      get
      {
        return this.constructionField;
      }
      set
      {
        this.constructionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public partial class Construction
  {

    private string ownerField;

    private VolumeObject[] volumeobjectField;

    public Construction()
    {
      this.ownerField = "VolumeObjectCoordinator";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("volumeobject", Order = 1)]
    public VolumeObject[] volumeobject
    {
      get
      {
        return this.volumeobjectField;
      }
      set
      {
        this.volumeobjectField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public partial class VolumeObject
  {

    private VolumeObjectClass_name class_nameField;

    private VolumeObjectRoot_penetration_probability root_penetration_probabilityField;

    private VolumeObjectPermeability permeabilityField;

    private string originField;

    private decimal depthField;

    private bool depthFieldSpecified;

    private decimal radiusField;

    private bool radiusFieldSpecified;

    private string leftfronttopField;

    private string rightbackbottomField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public VolumeObjectClass_name class_name
    {
      get
      {
        return this.class_nameField;
      }
      set
      {
        this.class_nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public VolumeObjectRoot_penetration_probability root_penetration_probability
    {
      get
      {
        return this.root_penetration_probabilityField;
      }
      set
      {
        this.root_penetration_probabilityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public VolumeObjectPermeability permeability
    {
      get
      {
        return this.permeabilityField;
      }
      set
      {
        this.permeabilityField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string origin
    {
      get
      {
        return this.originField;
      }
      set
      {
        this.originField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal depth
    {
      get
      {
        return this.depthField;
      }
      set
      {
        this.depthField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool depthSpecified
    {
      get
      {
        return this.depthFieldSpecified;
      }
      set
      {
        this.depthFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public decimal radius
    {
      get
      {
        return this.radiusField;
      }
      set
      {
        this.radiusField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified
    {
      get
      {
        return this.radiusFieldSpecified;
      }
      set
      {
        this.radiusFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string leftfronttop
    {
      get
      {
        return this.leftfronttopField;
      }
      set
      {
        this.leftfronttopField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string rightbackbottom
    {
      get
      {
        return this.rightbackbottomField;
      }
      set
      {
        this.rightbackbottomField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public enum VolumeObjectClass_name
  {

    /// <remarks/>
    BoundingCylinder,

    /// <remarks/>
    BoundingRectangularPrism,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public partial class VolumeObjectRoot_penetration_probability
  {

    private decimal topField;

    private decimal bottomField;

    private decimal sidesField;

    private VolumeObjectRoot_penetration_probabilityProbability_calculation_algorithm probability_calculation_algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public decimal top
    {
      get
      {
        return this.topField;
      }
      set
      {
        this.topField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public decimal bottom
    {
      get
      {
        return this.bottomField;
      }
      set
      {
        this.bottomField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public decimal sides
    {
      get
      {
        return this.sidesField;
      }
      set
      {
        this.sidesField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public VolumeObjectRoot_penetration_probabilityProbability_calculation_algorithm probability_calculation_algorithm
    {
      get
      {
        return this.probability_calculation_algorithmField;
      }
      set
      {
        this.probability_calculation_algorithmField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public enum VolumeObjectRoot_penetration_probabilityProbability_calculation_algorithm
  {

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Directly Specified")]
    DirectlySpecified,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Cosin Proportional")]
    CosinProportional,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://example.org/ROOTMAP/VolumeObjectsSchema")]
  public partial class VolumeObjectPermeability
  {

    private decimal topField;

    private decimal bottomField;

    private decimal sidesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public decimal top
    {
      get
      {
        return this.topField;
      }
      set
      {
        this.topField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public decimal bottom
    {
      get
      {
        return this.bottomField;
      }
      set
      {
        this.bottomField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public decimal sides
    {
      get
      {
        return this.sidesField;
      }
      set
      {
        this.sidesField = value;
      }
    }
  }
}
